import {
  CSharpIcon,
  GitIcon,
  GithubIcon,
  JavaScriptIcon,
  NodeJSIcon,
  CSSIcon,
  HTMLIcon,
  DotNetCoreIcon,
  ASPNetIcon,
  BootstrapIcon,
  PostgreSQLIcon,
  EnglishIcon,
} from "../assets/svg/index";

export const COURSES_OBJECT_LIST = [
  {
    title: "Object-Oriented Programming Course: OOP",
    institution: "Platzi",
    date: "March 2021",
    technologies: [CSharpIcon],
    url: "https://platzi.com/p/josephdavidortegacordova/curso/1474-oop/diploma/detalle/",
  },
  {
    title: "Basic Programming Course",
    institution: "Platzi",
    date: "March 2021",
    technologies: [JavaScriptIcon, CSSIcon, HTMLIcon, GitIcon, GithubIcon],
    url: "https://platzi.com/p/josephdavidortegacordova/curso/1050-programacion-basica/diploma/detalle/",
  },
  {
    title: "Professional Git and GitHub Course",
    institution: "Platzi",
    date: "March 2021",
    technologies: [JavaScriptIcon, GitIcon, GithubIcon],
    url: "https://platzi.com/p/josephdavidortegacordova/curso/1557-git-github/diploma/detalle/",
  },
  {
    title: "C# Fundamentals with .NET Core 2018",
    institution: "Platzi",
    date: "April 2021",
    technologies: [CSharpIcon, DotNetCoreIcon],
    url: "https://platzi.com/p/josephdavidortegacordova/curso/1375-fundamentos-csharp-2018/diploma/detalle/",
  },
  {
    title: "Basic Course in Algorithms and Logical Thinking",
    institution: "Platzi",
    date: "April 2021",
    technologies: [],
    url: "https://platzi.com/p/josephdavidortegacordova/curso/2218-course/diploma/detalle/",
  },
  {
    title: ".NET Core C# Course",
    institution: "Platzi",
    date: "July 2021",
    technologies: [CSharpIcon],
    url: "https://platzi.com/p/josephdavidortegacordova/curso/1359-c-sharp/diploma/detalle/",
  },
  {
    title: "ASP.NET Core Course",
    institution: "Platzi",
    date: "August 2021",
    technologies: [CSharpIcon, ASPNetIcon],
    url: "http://platzi.com/p/josephdavidortegacordova/curso/1395-aspnet-core/diploma/detalle/",
  },
  {
    title: "Full Stack JavaScript Application Development",
    institution: "Desafio Latam",
    date: "June 2022",
    technologies: [
      GitIcon,
      BootstrapIcon,
      GithubIcon,
      HTMLIcon,
      PostgreSQLIcon,
      JavaScriptIcon,
      CSSIcon,
      NodeJSIcon,
    ],
    url: "",
  },
  {
    title: "EF SET Certificate - C2",
    institution: "EF Standard English Test (EF SET) ",
    date: "July 2023",
    technologies: [EnglishIcon],
    url: "https://www.efset.org/cert/SvwPMo",
  },
];
